### ISSUE TITLE
Question: how can I see the transformed image?

### ISSUE THREAD

**Issue by lcipolina** [jacobdunefsky/conformal#1]
Hello, 
Thank you very much for your library. I have a couple of questions if you don't mind.

**1. How can I see the transformed image?**
When I run your code, I can only see the original image (see screenshot)

My code is simply:
>> python conformal.py think.png -t

**2. Where should I apply the "z" variable if I want to change the transformation?**

Thanks!

<img width="517" alt="thinking_screenshot" src="https://user-images.githubusercontent.com/5190890/85348202-d815fd00-b4c8-11ea-88d6-18c37af17dfa.PNG">

**Comment by jacobdunefsky** [comment]
After applying a transformation, the new transformed image should appear in the window in which the original image was displayed. As for inputting the transformation function, you should be able to type it in in the same terminal where you launched the program. I've attached an example screenshot, which should help.
![conformal_screenshot](https://user-images.githubusercontent.com/60287362/85786754-8e135e00-b6f8-11ea-85d5-54dd63a8545d.PNG)

**Comment by lcipolina** [comment]
Thank you very much for your reply. And congrats for your work.
I understood now that I have to type the transformation in the console!

Quick questions if you don't mind:

**1.** I guess if I want to pass the transformation as a parameter.. I will need to change this line here:

<img width="357" alt="code_to_change" src="https://user-images.githubusercontent.com/5190890/85798544-a3de4e80-b70b-11ea-8009-2bdc2d67f0b2.PNG">

**2.** What are the numbers appearing on the console? (10.043... in your case)

**3.** Stupid question: I've been trying different strategies, but I am not sure,  is it possible to apply a LOG to the picture? I want to achieve a tiling like this:

<img width="218" alt="Tiling" src="https://user-images.githubusercontent.com/5190890/85810110-fe85a380-b727-11ea-9c93-5506e3d407d2.PNG">

Which would be something like this:
<img width="491" alt="tiling2" src="https://user-images.githubusercontent.com/5190890/85810285-93889c80-b728-11ea-8c7a-b5d8f287290e.PNG">


Thank you very much!

**Comment by jacobdunefsky** [comment]
Thank you for the kind words. If you want to hard-code in the transformation that's applied, you can get rid of the line that you pointed out and replace line 41 (`myfunc = lambda z: eval(new_func)`) with the function that you wrote. For example, if you wrote a function
    def transformation_function(z):

        return (z/2)**2
then you could replace line 41 with `myfunc = transformation_function`.

As for the numbers in the console, that's the amount of time in seconds that the program took to render the transformation. Admittedly, it's not a fast algorithm, and I'm sure that there are faster ones (maybe ones that apply the transformation at progressively finer-grained levels of detail, so that even before the entire image is rendered, you can get a sense of what the final output would look like).

Finally, if you want to do a transformation that "unrolls" a circle, you'd actually use `cmath.exp(z)` instead of log. This is because of a peculiarity of the mapping software. The diagram that you posted colors each pixel in the image of the transformation with the color of the pixel that was mapped to that point. `conformal`, however, colors each pixel in the image of the transformation with the color of the pixel that the point gets mapped to. This means that you have to use the inverse function of the one that would give you the desired transformation.

**Comment by lcipolina** [comment]
Thank you very much Jacob for all these explanations. 

Everything is very clear now. I will close the open issue as all my questions have been answered.

Thanks again!
